/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as AdvanceRouteImport } from './routes/advance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvanceRoute = AdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advance': typeof AdvanceRoute
  '/jobs': typeof JobsRouteWithChildren
  '/learning': typeof LearningRoute
  '/profile': typeof ProfileRoute
  '/salary': typeof SalaryRoute
  '/skills': typeof SkillsRoute
  '/team': typeof TeamRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advance': typeof AdvanceRoute
  '/jobs': typeof JobsRouteWithChildren
  '/learning': typeof LearningRoute
  '/profile': typeof ProfileRoute
  '/salary': typeof SalaryRoute
  '/skills': typeof SkillsRoute
  '/team': typeof TeamRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advance': typeof AdvanceRoute
  '/jobs': typeof JobsRouteWithChildren
  '/learning': typeof LearningRoute
  '/profile': typeof ProfileRoute
  '/salary': typeof SalaryRoute
  '/skills': typeof SkillsRoute
  '/team': typeof TeamRoute
  '/jobs/$id': typeof JobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advance'
    | '/jobs'
    | '/learning'
    | '/profile'
    | '/salary'
    | '/skills'
    | '/team'
    | '/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advance'
    | '/jobs'
    | '/learning'
    | '/profile'
    | '/salary'
    | '/skills'
    | '/team'
    | '/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/advance'
    | '/jobs'
    | '/learning'
    | '/profile'
    | '/salary'
    | '/skills'
    | '/team'
    | '/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvanceRoute: typeof AdvanceRoute
  JobsRoute: typeof JobsRouteWithChildren
  LearningRoute: typeof LearningRoute
  ProfileRoute: typeof ProfileRoute
  SalaryRoute: typeof SalaryRoute
  SkillsRoute: typeof SkillsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advance': {
      id: '/advance'
      path: '/advance'
      fullPath: '/advance'
      preLoaderRoute: typeof AdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
  }
}

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvanceRoute: AdvanceRoute,
  JobsRoute: JobsRouteWithChildren,
  LearningRoute: LearningRoute,
  ProfileRoute: ProfileRoute,
  SalaryRoute: SalaryRoute,
  SkillsRoute: SkillsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
