// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geykkgepjqelqbkbkuvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdleWtrZ2VwanFlbHFia2JrdXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3MDEzMDUsImV4cCI6MjA5NTI3NzMwNX0.8wH-bz93TAtYc67FMhW9zfMkc5YTD0z2NUsqZGpcI8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});